language: php
cache:
  directories:
  - "$HOME/.composer/cache"
php:
  - '7.2'
script:
- cp .env.example .env
- php artisan key:generate
- vendor/bin/phpunit --coverage-clover=coverage.xml

install: composer install --no-interaction

after_success:
    - bash <(curl -s https://codecov.io/bash)
